version: "3"
services:
  frontend:
    image: frontend
    build: frontend
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    env_file:
      - .env.development
    network_mode: host
    ports:
      - "5173:5173"

  backend:
    image: backend
    build: backend/
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    network_mode: host
    ports:
      - "9000:9000"