version: "3.1"
services:
  backend:
    image: backend
    build: ./backend
    restart: always
    env_file:
      - .env
  frontend:
    image: frontend
    build: ./frontend
    restart: always
    stdin_open: true
    depends_on:
      - backend
    env_file:
      - .env
